### ISSUE TITLE
Client issue with oauth2 and ANONYMOUS_AUTH

### ISSUE THREAD

**Issue by pibou** [nuxeo/nuxeo-js-client#131]
Hi,

from a vanilla JS page, the call to authorizationURL does not redirect to login but directly to the configured redirect_uri
the call to fetchAccessTokenFromAuthorizationCode indeed creates a token ... for Guest user

In the PluggableAuthenticationService configuration, OAUTH2_AUTH is always before ANONYMOUS_AUTH in extension points chain or already overridden specificChains

What's wrong ?
PS : default auth is Shibboleth

**Comment by troger** [comment]
Hello,

Sorry for the late answer but you must append `forceAnonymousLogin=true` to the `authorizationURL` if you want to avoid the anonymous login in this case.
