### ISSUE TITLE
Nuxeo client breaking Angular-cli application on Firefox 50

### ISSUE THREAD

**Issue by gustavofp** [nuxeo/nuxeo-js-client#47]
Hello, 

I'm using the Nuxeo JS Client on an Angular 4 project and noticed that the lib breaks the application on Firefox 50, as the image shows. 

![image](https://user-images.githubusercontent.com/22947103/34730147-b8378a2a-f545-11e7-95e8-669b590d2c2d.png)

The problem is caused by a bug in Firefox itself (https://bugzilla.mozilla.org/show_bug.cgi?id=1101653) but we need to provide support to Firefox 50, so i'm opening this issue to relate to a pull-request that fix this problem.

**Comment by troger** [comment]
Fixed with 04b00aa.
