### ISSUE TITLE
Import a single export from a module

### ISSUE THREAD

**Issue by kodermax** [nuxeo/nuxeo-js-client#52]
Could you please make export module for import like this.
```
import { Nuxeo } from 'nuxeo';
```

**Comment by troger** [comment]
Why?

**Comment by kodermax** [comment]
Follow the standard ES6 Imports.

**Comment by troger** [comment]
You can already do the following:

```
import Nuxeo from 'nuxeo';
```

**Comment by kodermax** [comment]
I get error
![image](https://user-images.githubusercontent.com/590985/36276622-9668cefa-129f-11e8-94bb-03a551235753.png)

**Comment by troger** [comment]
Which version of the client do you use?
Which version of Angular?
Do you have a sample project reproducing the error? Or could it be reproduced with a bootstrap project or something?

**Comment by troger** [comment]
As Nuxeo is not a TypeScript module, you can do the following (tested on latest Angular version):

```
import * as Nuxeo from 'nuxeo';
```

**Comment by kodermax** [comment]
Thanks.
